// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Components.proto

#ifndef PROTOBUF_INCLUDED_Components_2eproto
#define PROTOBUF_INCLUDED_Components_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Components_2eproto 

namespace protobuf_Components_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Components_2eproto
class Component;
class ComponentDefaultTypeInternal;
extern ComponentDefaultTypeInternal _Component_default_instance_;
class Components;
class ComponentsDefaultTypeInternal;
extern ComponentsDefaultTypeInternal _Components_default_instance_;
class SWTPoint_buf;
class SWTPoint_bufDefaultTypeInternal;
extern SWTPoint_bufDefaultTypeInternal _SWTPoint_buf_default_instance_;
namespace google {
namespace protobuf {
template<> ::Component* Arena::CreateMaybeMessage<::Component>(Arena*);
template<> ::Components* Arena::CreateMaybeMessage<::Components>(Arena*);
template<> ::SWTPoint_buf* Arena::CreateMaybeMessage<::SWTPoint_buf>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class SWTPoint_buf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SWTPoint_buf) */ {
 public:
  SWTPoint_buf();
  virtual ~SWTPoint_buf();

  SWTPoint_buf(const SWTPoint_buf& from);

  inline SWTPoint_buf& operator=(const SWTPoint_buf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SWTPoint_buf(SWTPoint_buf&& from) noexcept
    : SWTPoint_buf() {
    *this = ::std::move(from);
  }

  inline SWTPoint_buf& operator=(SWTPoint_buf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SWTPoint_buf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SWTPoint_buf* internal_default_instance() {
    return reinterpret_cast<const SWTPoint_buf*>(
               &_SWTPoint_buf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SWTPoint_buf* other);
  friend void swap(SWTPoint_buf& a, SWTPoint_buf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SWTPoint_buf* New() const final {
    return CreateMaybeMessage<SWTPoint_buf>(NULL);
  }

  SWTPoint_buf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SWTPoint_buf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SWTPoint_buf& from);
  void MergeFrom(const SWTPoint_buf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SWTPoint_buf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // int32 y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // float SWT = 3;
  void clear_swt();
  static const int kSWTFieldNumber = 3;
  float swt() const;
  void set_swt(float value);

  // @@protoc_insertion_point(class_scope:SWTPoint_buf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  float swt_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Components_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Component : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Component) */ {
 public:
  Component();
  virtual ~Component();

  Component(const Component& from);

  inline Component& operator=(const Component& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Component(Component&& from) noexcept
    : Component() {
    *this = ::std::move(from);
  }

  inline Component& operator=(Component&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Component& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Component* internal_default_instance() {
    return reinterpret_cast<const Component*>(
               &_Component_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Component* other);
  friend void swap(Component& a, Component& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Component* New() const final {
    return CreateMaybeMessage<Component>(NULL);
  }

  Component* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Component>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Component& from);
  void MergeFrom(const Component& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Component* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SWTPoint_buf points = 1;
  int points_size() const;
  void clear_points();
  static const int kPointsFieldNumber = 1;
  ::SWTPoint_buf* mutable_points(int index);
  ::google::protobuf::RepeatedPtrField< ::SWTPoint_buf >*
      mutable_points();
  const ::SWTPoint_buf& points(int index) const;
  ::SWTPoint_buf* add_points();
  const ::google::protobuf::RepeatedPtrField< ::SWTPoint_buf >&
      points() const;

  // int32 maxX = 2;
  void clear_maxx();
  static const int kMaxXFieldNumber = 2;
  ::google::protobuf::int32 maxx() const;
  void set_maxx(::google::protobuf::int32 value);

  // int32 minX = 3;
  void clear_minx();
  static const int kMinXFieldNumber = 3;
  ::google::protobuf::int32 minx() const;
  void set_minx(::google::protobuf::int32 value);

  // int32 maxY = 4;
  void clear_maxy();
  static const int kMaxYFieldNumber = 4;
  ::google::protobuf::int32 maxy() const;
  void set_maxy(::google::protobuf::int32 value);

  // int32 minY = 5;
  void clear_miny();
  static const int kMinYFieldNumber = 5;
  ::google::protobuf::int32 miny() const;
  void set_miny(::google::protobuf::int32 value);

  // float width = 6;
  void clear_width();
  static const int kWidthFieldNumber = 6;
  float width() const;
  void set_width(float value);

  // float height = 7;
  void clear_height();
  static const int kHeightFieldNumber = 7;
  float height() const;
  void set_height(float value);

  // float mean = 8;
  void clear_mean();
  static const int kMeanFieldNumber = 8;
  float mean() const;
  void set_mean(float value);

  // float SD = 9;
  void clear_sd();
  static const int kSDFieldNumber = 9;
  float sd() const;
  void set_sd(float value);

  // float WV = 10;
  void clear_wv();
  static const int kWVFieldNumber = 10;
  float wv() const;
  void set_wv(float value);

  // float AR = 11;
  void clear_ar();
  static const int kARFieldNumber = 11;
  float ar() const;
  void set_ar(float value);

  // float OR = 12;
  void clear_or_();
  static const int kORFieldNumber = 12;
  float or_() const;
  void set_or_(float value);

  // float characteristic_scale = 13;
  void clear_characteristic_scale();
  static const int kCharacteristicScaleFieldNumber = 13;
  float characteristic_scale() const;
  void set_characteristic_scale(float value);

  // float orientation = 14;
  void clear_orientation();
  static const int kOrientationFieldNumber = 14;
  float orientation() const;
  void set_orientation(float value);

  // float center_x = 15;
  void clear_center_x();
  static const int kCenterXFieldNumber = 15;
  float center_x() const;
  void set_center_x(float value);

  // float center_y = 16;
  void clear_center_y();
  static const int kCenterYFieldNumber = 16;
  float center_y() const;
  void set_center_y(float value);

  // @@protoc_insertion_point(class_scope:Component)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::SWTPoint_buf > points_;
  ::google::protobuf::int32 maxx_;
  ::google::protobuf::int32 minx_;
  ::google::protobuf::int32 maxy_;
  ::google::protobuf::int32 miny_;
  float width_;
  float height_;
  float mean_;
  float sd_;
  float wv_;
  float ar_;
  float or__;
  float characteristic_scale_;
  float orientation_;
  float center_x_;
  float center_y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Components_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Components : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Components) */ {
 public:
  Components();
  virtual ~Components();

  Components(const Components& from);

  inline Components& operator=(const Components& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Components(Components&& from) noexcept
    : Components() {
    *this = ::std::move(from);
  }

  inline Components& operator=(Components&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Components& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Components* internal_default_instance() {
    return reinterpret_cast<const Components*>(
               &_Components_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Components* other);
  friend void swap(Components& a, Components& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Components* New() const final {
    return CreateMaybeMessage<Components>(NULL);
  }

  Components* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Components>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Components& from);
  void MergeFrom(const Components& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Components* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Component components = 1;
  int components_size() const;
  void clear_components();
  static const int kComponentsFieldNumber = 1;
  ::Component* mutable_components(int index);
  ::google::protobuf::RepeatedPtrField< ::Component >*
      mutable_components();
  const ::Component& components(int index) const;
  ::Component* add_components();
  const ::google::protobuf::RepeatedPtrField< ::Component >&
      components() const;

  // @@protoc_insertion_point(class_scope:Components)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Component > components_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Components_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SWTPoint_buf

// int32 x = 1;
inline void SWTPoint_buf::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 SWTPoint_buf::x() const {
  // @@protoc_insertion_point(field_get:SWTPoint_buf.x)
  return x_;
}
inline void SWTPoint_buf::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SWTPoint_buf.x)
}

// int32 y = 2;
inline void SWTPoint_buf::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 SWTPoint_buf::y() const {
  // @@protoc_insertion_point(field_get:SWTPoint_buf.y)
  return y_;
}
inline void SWTPoint_buf::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SWTPoint_buf.y)
}

// float SWT = 3;
inline void SWTPoint_buf::clear_swt() {
  swt_ = 0;
}
inline float SWTPoint_buf::swt() const {
  // @@protoc_insertion_point(field_get:SWTPoint_buf.SWT)
  return swt_;
}
inline void SWTPoint_buf::set_swt(float value) {
  
  swt_ = value;
  // @@protoc_insertion_point(field_set:SWTPoint_buf.SWT)
}

// -------------------------------------------------------------------

// Component

// repeated .SWTPoint_buf points = 1;
inline int Component::points_size() const {
  return points_.size();
}
inline void Component::clear_points() {
  points_.Clear();
}
inline ::SWTPoint_buf* Component::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:Component.points)
  return points_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::SWTPoint_buf >*
Component::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:Component.points)
  return &points_;
}
inline const ::SWTPoint_buf& Component::points(int index) const {
  // @@protoc_insertion_point(field_get:Component.points)
  return points_.Get(index);
}
inline ::SWTPoint_buf* Component::add_points() {
  // @@protoc_insertion_point(field_add:Component.points)
  return points_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SWTPoint_buf >&
Component::points() const {
  // @@protoc_insertion_point(field_list:Component.points)
  return points_;
}

// int32 maxX = 2;
inline void Component::clear_maxx() {
  maxx_ = 0;
}
inline ::google::protobuf::int32 Component::maxx() const {
  // @@protoc_insertion_point(field_get:Component.maxX)
  return maxx_;
}
inline void Component::set_maxx(::google::protobuf::int32 value) {
  
  maxx_ = value;
  // @@protoc_insertion_point(field_set:Component.maxX)
}

// int32 minX = 3;
inline void Component::clear_minx() {
  minx_ = 0;
}
inline ::google::protobuf::int32 Component::minx() const {
  // @@protoc_insertion_point(field_get:Component.minX)
  return minx_;
}
inline void Component::set_minx(::google::protobuf::int32 value) {
  
  minx_ = value;
  // @@protoc_insertion_point(field_set:Component.minX)
}

// int32 maxY = 4;
inline void Component::clear_maxy() {
  maxy_ = 0;
}
inline ::google::protobuf::int32 Component::maxy() const {
  // @@protoc_insertion_point(field_get:Component.maxY)
  return maxy_;
}
inline void Component::set_maxy(::google::protobuf::int32 value) {
  
  maxy_ = value;
  // @@protoc_insertion_point(field_set:Component.maxY)
}

// int32 minY = 5;
inline void Component::clear_miny() {
  miny_ = 0;
}
inline ::google::protobuf::int32 Component::miny() const {
  // @@protoc_insertion_point(field_get:Component.minY)
  return miny_;
}
inline void Component::set_miny(::google::protobuf::int32 value) {
  
  miny_ = value;
  // @@protoc_insertion_point(field_set:Component.minY)
}

// float width = 6;
inline void Component::clear_width() {
  width_ = 0;
}
inline float Component::width() const {
  // @@protoc_insertion_point(field_get:Component.width)
  return width_;
}
inline void Component::set_width(float value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:Component.width)
}

// float height = 7;
inline void Component::clear_height() {
  height_ = 0;
}
inline float Component::height() const {
  // @@protoc_insertion_point(field_get:Component.height)
  return height_;
}
inline void Component::set_height(float value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:Component.height)
}

// float mean = 8;
inline void Component::clear_mean() {
  mean_ = 0;
}
inline float Component::mean() const {
  // @@protoc_insertion_point(field_get:Component.mean)
  return mean_;
}
inline void Component::set_mean(float value) {
  
  mean_ = value;
  // @@protoc_insertion_point(field_set:Component.mean)
}

// float SD = 9;
inline void Component::clear_sd() {
  sd_ = 0;
}
inline float Component::sd() const {
  // @@protoc_insertion_point(field_get:Component.SD)
  return sd_;
}
inline void Component::set_sd(float value) {
  
  sd_ = value;
  // @@protoc_insertion_point(field_set:Component.SD)
}

// float WV = 10;
inline void Component::clear_wv() {
  wv_ = 0;
}
inline float Component::wv() const {
  // @@protoc_insertion_point(field_get:Component.WV)
  return wv_;
}
inline void Component::set_wv(float value) {
  
  wv_ = value;
  // @@protoc_insertion_point(field_set:Component.WV)
}

// float AR = 11;
inline void Component::clear_ar() {
  ar_ = 0;
}
inline float Component::ar() const {
  // @@protoc_insertion_point(field_get:Component.AR)
  return ar_;
}
inline void Component::set_ar(float value) {
  
  ar_ = value;
  // @@protoc_insertion_point(field_set:Component.AR)
}

// float OR = 12;
inline void Component::clear_or_() {
  or__ = 0;
}
inline float Component::or_() const {
  // @@protoc_insertion_point(field_get:Component.OR)
  return or__;
}
inline void Component::set_or_(float value) {
  
  or__ = value;
  // @@protoc_insertion_point(field_set:Component.OR)
}

// float characteristic_scale = 13;
inline void Component::clear_characteristic_scale() {
  characteristic_scale_ = 0;
}
inline float Component::characteristic_scale() const {
  // @@protoc_insertion_point(field_get:Component.characteristic_scale)
  return characteristic_scale_;
}
inline void Component::set_characteristic_scale(float value) {
  
  characteristic_scale_ = value;
  // @@protoc_insertion_point(field_set:Component.characteristic_scale)
}

// float orientation = 14;
inline void Component::clear_orientation() {
  orientation_ = 0;
}
inline float Component::orientation() const {
  // @@protoc_insertion_point(field_get:Component.orientation)
  return orientation_;
}
inline void Component::set_orientation(float value) {
  
  orientation_ = value;
  // @@protoc_insertion_point(field_set:Component.orientation)
}

// float center_x = 15;
inline void Component::clear_center_x() {
  center_x_ = 0;
}
inline float Component::center_x() const {
  // @@protoc_insertion_point(field_get:Component.center_x)
  return center_x_;
}
inline void Component::set_center_x(float value) {
  
  center_x_ = value;
  // @@protoc_insertion_point(field_set:Component.center_x)
}

// float center_y = 16;
inline void Component::clear_center_y() {
  center_y_ = 0;
}
inline float Component::center_y() const {
  // @@protoc_insertion_point(field_get:Component.center_y)
  return center_y_;
}
inline void Component::set_center_y(float value) {
  
  center_y_ = value;
  // @@protoc_insertion_point(field_set:Component.center_y)
}

// -------------------------------------------------------------------

// Components

// repeated .Component components = 1;
inline int Components::components_size() const {
  return components_.size();
}
inline void Components::clear_components() {
  components_.Clear();
}
inline ::Component* Components::mutable_components(int index) {
  // @@protoc_insertion_point(field_mutable:Components.components)
  return components_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Component >*
Components::mutable_components() {
  // @@protoc_insertion_point(field_mutable_list:Components.components)
  return &components_;
}
inline const ::Component& Components::components(int index) const {
  // @@protoc_insertion_point(field_get:Components.components)
  return components_.Get(index);
}
inline ::Component* Components::add_components() {
  // @@protoc_insertion_point(field_add:Components.components)
  return components_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Component >&
Components::components() const {
  // @@protoc_insertion_point(field_list:Components.components)
  return components_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Components_2eproto
